jetson_1:
  ros_parameters:
    device: 'jetson_1'
    camera_type: 'blackfly_s'                         # declares camera type
    serial: "'21502646'"                              # sets camera serial for connection
    sonar: 'false'                                    # sonar launch boolean
    cam_topic: '/jetson_1/image/compressed'           # sets topic gui displays
    # The following parameters are for flir camera
    debug: 'False'    
    compute_brightness: 'False'    
    adjust_timestamp: 'True'    
    dump_node_map: 'False'    
    gain_auto: 'Continuous'    
    exposure_auto: 'Continuous'    
    user_set_selector: 'UserSet0'    
    user_set_load: 'Yes'    
    frame_rate_auto: 'Off'    
    frame_rate: '20.0'    
    frame_rate_enable: 'True'    
    buffer_queue_size: '10'    
    trigger_mode: 'Off'    
    chunk_mode_active: 'True'    
    chunk_selector_frame_id: 'FrameID'    
    chunk_enable_frame_id: 'True'    
    chunk_selector_exposure_time: 'ExposureTime'    
    chunk_enable_exposure_time: 'True'    
    chunk_selector_gain: 'Gain'    
    chunk_enable_gain: 'True'    
    chunk_selector_timestamp: 'Timestamp'    
    chunk_enable_timestamp: 'True'    

jetson_2:
  ros_parameters:
    device: 'jetson_2'
    camera_type: 'blackfly_s'                         # declares camera type
    serial: "'21387972'"                              # sets camera serial for connection
    sonar: 'true'                                    # sonar launch boolean
    cam_topic: '/jetson_2/image/compressed'           # sets topic gui displays
    # The following parameters are for flir camera
    debug: 'False'    
    compute_brightness: 'False' 
    adjust_timestamp: 'True'    
    dump_node_map: 'False'    
    gain_auto: 'Continuous'    
    exposure_auto: 'Continuous'    
    user_set_selector: 'UserSet0'    
    user_set_load: 'Yes'    
    frame_rate_auto: 'Off'    
    frame_rate: '20.0'    
    frame_rate_enable: 'True'    
    buffer_queue_size: '10'    
    trigger_mode: 'Off'    
    chunk_mode_active: 'True'    
    chunk_selector_frame_id: 'FrameID'    
    chunk_enable_frame_id: 'True'    
    chunk_selector_exposure_time: 'ExposureTime'    
    chunk_enable_exposure_time: 'True'    
    chunk_selector_gain: 'Gain'    
    chunk_enable_gain: 'True'    
    chunk_selector_timestamp: 'Timestamp'    
    chunk_enable_timestamp: 'True'  
